apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: docker-build-django-ex
spec:
  output:
    to:
      kind: ImageStreamTag
      name: docker-build-django-ex:latest
  source:
    git:
      uri: https://github.com/mosuke5/django-ex
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
    type: Docker
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: docker-build-django
